title: DTA Design Guide
description: >-
  A design guide for building Australian Government services with <a
  href="https://github.com/AusDTO/gov-au-ui-kit" rel="external">UI-Kit CSS
  framework</a>.
github_url: 'https://github.com/AusDTO/dto-design-guide'
uikit_github_url: 'https://github.com/AusDTO/gov-au-ui-kit'
uikit_base_url: 'https://gov-au-ui-kit.apps.staging.digital.gov.au/'
markdown: kramdown
exclude:
  - node_modules
  - _data
  - vendor
  - bin
  - .DS_Store
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - circle.yml
  - _config*.yml
  - config.ru
  - ld_library_path
  - LICENSE.md
  - manifest*.yml
  - yarn.lock
  - README.md
  - '*.sublime-project'
gems:
  - jekyll-assets
  - rouge
assets:
  assets:
    - '*.png'
    - '*.gif'
    - '*.svg'
  sources:
    - _assets/scss
    - _assets/vendor/dto-ui-kit/assets/sass/ui-kit
    - _assets/img
    - _assets/js
highlighter: rouge
collections:
  getting-started:
    output: true
    title: Getting started
    abstract: Design system principles and basics for designers and developers.
    order: 0
  foundations:
    output: true
    title: Foundations
    abstract: 'Guidance on the UI-Kit core modules: typography, layout and colours.'
    order: 1
  components:
    output: true
    title: Components
    abstract: >-
      How to use the building blocks of UI‑Kit: forms and buttons, list styles,
      accordions, badges and tables.
    order: 2
  patterns:
    output: true
    title: Patterns
    abstract: >-
      We are building a library of patterns that meet user needs. Find guidance
      on global, local and inline navigation.
    order: 3
  templates:
    output: true
    title: Templates
    abstract: We are working on templates for common types of service pages.
    order: 4
defaults:
  - scope:
      path: _getting-started
    values:
      parent: getting-started
      children:
        - folder: design-principles
          title: Design principles
        - folder: Developers
          title: For developers
  - scope:
      path: _foundations
    values:
      parent: foundations
      children:
        - folder: typography
          title: Typography
        - folder: layout
          title: Layout
        - folder: colours
          title: Colours
  - scope:
      path: _components
    values:
      parent: components
      children:
        - folder: forms-buttons
          title: Forms & buttons
        - folder: link-styles
          title: Link styles
        - folder: accordions
          title: Accordions
        - folder: badges
          title: Badges
        - folder: list styles
          title: List styles
        - folder: tables
          title: Tables
  - scope:
      path: _patterns
    values:
      parent: patterns
      children:
        - folder: navigation
          title: Navigation
        - folder: calendar-table
          title: Calendar table
        - folder: callouts
          title: Callouts
  - scope:
      path: _templates
    values:
      parent: templates
      children: null
baseurl: ''
url: ''
